### ISSUE TITLE
Hyperion Accessing Non-Existent Video Devices

### ISSUE THREAD

**Issue by sakis-tech** [foorschtbar/hyperion-docker#6]
I've set up the [hyperion-docker](https://github.com/foorschtbar/hyperion-docker) on my Raspberry Pi. The configuration specifies only one video device (`/dev/video0`), but the system tries to access multiple non-existent video devices, leading to a series of errors in the logs. This behavior seems incorrect as only one video device is intended to be used.

**Docker-Compose Configuration:**

```yaml
services:
  hyperion:
    image: foorschtbar/hyperion
    container_name: hyperion
    ports:
      - 8090:8090
      - 8091:8091
      - 19444:19444
      - 19445:19445
    volumes:
      - ./config/:/root/.hyperion
    devices:
      - /dev/video0:/dev/video0
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    restart: unless-stopped
```

**Logs:**

```
2024-07-30T20:19:52.751 |__| V4L2              : <ERROR> Throws error nr: Cannot open '/dev/video14' error code 2, No such file or directory
2024-07-30T20:19:52.751 |__| V4L2              : <ERROR> Throws error nr: Cannot open '/dev/video22' error code 2, No such file or directory
...
2024-07-30T20:19:52.755 |__| V4L2              : <ERROR> Throws error nr: Cannot open '/dev/video16' error code 2, No such file or directory
```

**System Details:**
- OS: **Raspbian GNU/Linux 11 (bullseye)**
- Hyperion Version: **2.0.16**
- Docker Version:  **27.1.1, build 6312585**

**Steps to Reproduce:**
1. Set up the Docker container using the above `docker-compose` configuration.
2. Start the container and observe the logs.

**Expected Behavior:**
Hyperion should only attempt to access the video device specified (`/dev/video0`).

**Actual Behavior:**
Hyperion attempts to access multiple non-existent video devices, which results in error messages.

**Additional Information:**
The Docker container has the correct permissions, and the specified video device is properly configured and accessible. It seems like Hyperion is not respecting the specified device or there may be a misconfiguration.

Any guidance or fix would be appreciated!
